#!/usr/bin/env python
# -*- coding:utf-8 -*-
#制作:温赫男

'''
'''


import os
import logging
def initenv():
    import sys
    sys.path.append("config")
    import define
    if not os.path.exists(define.RESULT_PATH):
        os.mkdir(define.RESULT_PATH)

    if not os.path.exists(define.XML_RESULT_PATH):
        os.mkdir(define.XML_RESULT_PATH)
    if not os.path.exists(define.OUTPUT_PATH):
        os.mkdir(define.OUTPUT_PATH)


    logger = logging.getLogger("")
    logger.setLevel(logging.INFO)
initenv()
import publog
import model
import trans
import json
import define
def Haha():
    try:
        1/0
    except Exception as e:
        print e
        logging.exception("sdf",exc_info=1)
        #import  traceback
        #traceback.print_exc()

def ColorPrint(*args):
    print '\033[1;31;40m'
    print ",".join([str(i) for i in args])
    print '\033[0m'

def main():
    model.InitData()
    # model.CSaveData.Restart()
    # model.CSaveData.c_StartTime = "2017-05-11T00:00:00"
    # model.CSaveData.c_EndTime = "2017-05-20T00:00:00"
    # trans.Get_GroupIDList("A3")
    # model.CSaveData.DoSave()
    # return

    if not model.CSaveData.ReadSaveData():
        publog.error("需要初始化数据,请配置文件",define.CONFIG_FILE)

        return
    model.CSaveData.c_StartTime = "2017-03-31T00:00:00"#设置开始时间
    model.CSaveData.c_EndTime = "2017-06-27T00:00:00"#设置结束时间时间

    model.CSaveData.c_GroupID_List = {}
    model.CSaveData.c_SaveList = {}
    model.CSaveData.c_StoreList = [#设置店铺列表
        "A4",
        "A3",
        "A1",
        "A2",
        "A5",
        "A7",
        "A9",
        "A10",
        "C1A5",
        "C1A7",
        "C1A10",
        "B6",
        "B11",
        "B8",
        "U1A7",
        "J1A9",
        "J2A10",
        "J2A7",
        "B15",
        "B16",
        "B17",
        "B14",
        "B13",
        "B12",
        "B18",
        "B19",
        "HZToyota",
        "SHByd",
        "YTVolkswagen",
        "Houston",
        "Chicago",
        "New York",
        "St Paul",
        "U2A14",
        "vancouver",
        "QingDao",
        "QDMazda",
        "Audius",
        "usbrothers",
        "SZFord",
        "Seattle",
        "Boston-WX",
        "TokyoMall",
        "jppartner",
        "SportyMal",
        "Toronto-C",
        "YanTai",
        "SZBMW",
        "QDVolvo",
        "QDJaguar",
        "SZDS",
        "BJBuick",
        "JiNan",
        "Alaska",
        "DaLian",
        "HangZhou",
        "Miami-WX",
        "Detroit-WX",
        "Thinkmax",
        "Casie",
        "Los Angeles-WX",
        "Ottawa",
        "petsmart",
        "Pittsburgh",
        "Washington-WX",
        "XiaMen",
        "ChengDu",
        "ShangHai",
        "NingBo",
        "Hawaii-WX",
        "ChongQing",
        "ZheJiang",
        "JiLin",
        "LiaoNing",
        "ShanDong",
        "Philadelphia",
        "Weihai",
        "Sherbrooke",
        "BoBo",
        "TaiZhou",
        "TianJin",
        "NanJing",
        "ShanTou",
        "HeBei",
        "JiangSu",
        "HuNan",
        "FuJian",
        "HuBei",
        "HongKong",
        "Mexico",
        "haerbin",
        "ZiBo",
        "NingXia",
        "BinBin",
        "Mississippi",
        "Prada",
        "Tiffany",
        "ezyy",
        "X-45C",
        "F784",
        "Fendi",
        "X-50A",
        "U3",
        "zhongshan",
        "Helena",
        "Gucci",
        "Nevada",
        "Kansas",
        "ASN-206",
        "Kentucky",
        "Dover",
        "Maryland",
        "zhuhai",
        "Maya",
        "Pierre Cardin",
        "Lansing",
        "Oregon",
        "CableAccessories",
        "Chrysler",
        "Topeka",
        "Colorado",
        "Chrysler-C",
        "Chrysler-M",
        "Pierre Cardin-M",
        "CableAccessories_M",
        "Lincoln",
        "Lincoln-C",
        "Lincoln-M",
        "Toronto",
        "JiYun",
        "OberLin",
        "OberLin-C",
        "OberLin-M",
        "Chanel",
        "M60C",
        "yangzhou",
        "RQ-8A",
        "Sunshine",
        "Richmond",
        "California-WX",
        "AnHui",
        "Belle",
        "U4",
        "Indiana",
        "Bismarck-WX",
        "TaiZhou-C",
        "JinFeng-JP",
        "Hartford",
        "Dragonnest",
        "Portland",
        "Portland-M",
        "Portland-C",
        "Montreal",
        "Montreal-C",
        "Calgary",
        "Calgary-C",
        "Milwaukee",
        "Victoria",
        "Phoenix",
        "Phoenix-C",
        "Wisconsin",
        "Wisconsin-M",
        "Wisconsin-C",
        "Lansing-C",
        "Lansing-M",
        "Mountain",
        "Glendale",
        "Glendale-C",
        "Tscience",
        "Tscience-C",
        "Lubbock",
        "Austin",
        "Columbus",
        "Oscar",
        "D3",
        "D4",
        "Tillerson",
        "Daimler",
        "Hasee",
        "Chevron",
        "Berkshire",
        "Mckesson",
        "alienware",
        "alienware-C",
        "alienware-M",
        "Fannie",
        "U5",
        "D5",
        "UCloth",
        "DCloth",
        "Ujewelry",
        "Djewelry",
        "Dalian-C",
        "Renault",
        "Repsol",
        "VINCI",
        "JBS",
        "Barclays",
        "Uouthome",
        "Lukoil",
        "Aurora",
        "Anaheim",
        "Aurora",
        "Costco",
        "Utoys",
        "Ufashion",
        "NIPPON",
        "Kroger",
        "Ucalend",
        "Alaska_CA",
        "yangzhou_CA",
        "F784_CA",
        "Daimler_CA",
        "Nissan",
        "Nissan_CA",
        "St Paul_CA",
        "FUJITSU",
        "Zaandam",
        "Greenland",
        "NIPPON_CA",
        "Dcalend",
        "Austin_CA",
        "Hezhi",
        "Houston_CA",
        "ESCland",
        "Vancouver_US",
        "Zaandam_M",
        "Mexico_US",
        "Sherbrooke_US",
        "Fcalend",
        "ITCland",
        "EvenDream",
        "Futureql",
        "MoonSharon",
        "Courseby",
        "XiaMen_CA",
        "Berkeley",
        "Thinkmax_CA",
        "Audius_C",
        "F4",
        "NankyJp",
        "M60C_CA",
        "CableAccessories_CA",
        "Zaandam_CA",
        "Stanford",
        "Stanford_CA",
        "Harvard",
        "Barclays_CA",
        "ezyy_CA",
        "Eouthome",
        "compal",
        "Everbright",
        "Mckesson-CA",
        "Anaheim-CA",
        "Lightroom",
        "SZhuoJP",
        "EvenDream-CA",
        "Ffashion",
        "JiLin_CA",
        "HangZhou_CA",
        "Tiffany_CA",
        "ASN-206_CA",
        "Helena CA",
        "Tillerson_CA",
        "DYTesa",
        "QDMazda_CA",
        "QXBshike",
        "Cambridge",
        "LCYuan",
        "Berklee",
        "Ytoto",
        "KCChuangJP",
        "X-45C_CA",
        "POSCO",
        "Uapparel",
        "Dapparel",
        "Eapparel",
        "Fapparel",
        "Uleadingstar",
        "Dleadingstar",
        "Fleadingstar",
        "Maliet",
        "haerbin_CA",
        "Gucci_CA",
        "ITOCHU",
        "Fannie",
        "Francisco",
        "Utah",
        "Wedbration",
        "Unilever",
        "sunshine_CA",
        "Novartis",
        "Novartis_CA",
        "usbrothers_CA",
        "Fjewelry",
        "Prada_CA",
        "Landing",
        "jiangxi",
        "Mountain_CA",
        "F3",
        "Futureql_CA",
        "Ukeling",
        "Fkeling",
        "Dkeling",
        "GreatWall",
        "GreatWall_CA",
        "Douthome",
        "Fouthome",
        "California_CA",
        "DFashion",
        "Wedbration_CA",
        "Taian",
        "Taian_CA",
        "MoonSharon_CA",
        "Toppink",
        "Arlington",
        "Acekool",
        "DKoelner",
        "UKoelner",
        "FKoelner",
        "usbrothers_MX",
        "QiXia",
        "QiXia_CA",
        "Ashleytoys",
        "Chukoo",
        "DellDream",
        "KitKids",
        "Francisco_CA",
        "B14_CA",
        "HappyCenter",
        "JBS_CA",
        "Lankeling",
        "Prada_M",
        "LCYuan_CA",
        "Acekid",
        "SuperMan",
        "YoungHorse",
        "Superior",
        "Berklee_CA",
        "Zehui-C",
        "Albert_N",
        "Huron",
        "LenovoH",
        "AKDSteel",
        "YukiMall",
        "Wormald",
        "Oscar_CA",
        "Bismarck_CA",
        "Berkshire_CA",
        "Antoniohell",
        "FTDSakiyr",
        "Union",
        "Union_CA",
        "Sun_CA",
        "Sun",
        "Cambridge_CA",
        "helloNadia",
        "WF-1",
        "Lubbock_CA",
        "Topeka_CA",
        "RiseDream",
        "BingE",
        "Nagoya",
        "Sakala",
        "Zastyle",
        "ZishiUS",
        "MyHansen",
        "DHalloween",
        "KathyMall",
        "FanyMoon",
        "MyBarbie",
        "YRLED",
        "EdinburghUK",
        "CardiffUK",
        "LiverpoolUK",
        "GlasgowUK",
        "Sparkling",
        "Sparkling_CA",
        "Sparkling_MX",
        "Kroger_CA",
        "LenovoH_CA",
        "LenovoH_MX",
        "Ganzhou",
        "ESKoelner",
        "MyHansen_CA",
        "Damai",
        "Michigan",
        "Louisiana",
        "KelingJP",
        "BelfastUK",
        "Lankeling_CA",
        "YTVolkswagen_CA",
        "Wuqiong",
        "ZishiUS_CA",
        "POSCO_CA",
        "RiseDream_CA",
        "RiseDream_MX",
        "BingE_CA",
        "BingE_MX",
        "Inmars",
        "PlymouthUS",
        "PlymouthUK",
        "PlymouthDE",
        "PlymouthFR",
        "Albany",
        "Albany_CA",
        "Eureka",
        "ChrislyH",
        "TomYStore",
        "BristolUK",
        "NewcastleUK",
        "Dragonnest_CA",
        "APPLUS",
        "Minnesota",
        "Casio",
        "SonyY",
        "CAROMIO",
        "ShanTou_CA",
        "Damai_CA",
        "DYTesa_CA",
        "Chunli",
        "Chunli_CA",
        "Chunli_MX",
        "Laptop",
        "Laptop_CA",
        "Laptop_MX",
        "LvzhongJP",
        "Washington_CA",
        "Florible",
        "Florible_CA",
        "Monster",
        "Monster_CA",
        "DHalloween_CA",
        "SongyeUK",
        "ZiningUK",
        "Shirly",
        "Reading_CA",
        "Bigman_CA",
        "Bigman",
        "Reading",
        "Glasgow_DE",
        "Indiana_CA",
        "Amazbox",
        "ShanDong_CA",
        "Casio_CA",
        "NewcastleDE",
        "NewcastleFR",
        "Pretty",
        "Pretty_CA",
        "Pretty_MX",
        "CardiffDE",
        "CardiffES",
        "Champion",
        "Shirly_CA",
        "Shirly_MX",
        "Champion_CA",
        "Champion_MX",
        "hellotoysme",
        "hellotoysme_CA",
        "Wormald_CA",
        "BelfastDE",
        "BelfastFR",
        "Jefferson",
        "Jefferson_CA",
        "NanJing_CA",
        "Pierre Cardin_CA",
        "XiamoJP",
        "Louisiana_CA",
        "SongyeJP",
        "Hihoddy_UK",
        "AKDSteel_CA",
        "YRLED_CA",
        "Happyers",
        "Hihoddy_IT",
        "Hihoddy_FR",
        "Hihoddy_ES",
        "Hihoddy_DE",
        "GlasgowIT",
        "GlasgowES",
        "GlasgowFR",
        "ZiningUS",
        "CNkansal",
        "XiamoUS",
        "Hihoddy-JP",
        "WF-1_CA",
        "YihaiJP",
        "ZiningJP",
        "EdinburghDE",
        "EdinburghFR",
        "EdinburghES",
        "EdinburghIT",
        "PlymouthES",
        "PlymouthIT",
        "Michigan-C",
        "leilanJP",
        "LanleiUK",
        "LanleiDE",
        "LanleiES",
        "LanleiFR",
        "LanleiIT",
        "LanleiUS",
        "LanleiCA",
        "LanleiMX",
        "LuomingUK",
        "LuomingDE",
        "LuomingES",
        "LuomingFR",
        "LuomingIT",
        "YunmiaoUS",
        "YunmiaoCA",
        "YunmiaoMX",
        "HuangzongUS",
        "ColumbCA",
        "Minnesota_CA",
        "Kumorefun_US",
        "Kumorefun_CA",
        "Kumorefun_MX",
        "LuomingJP",
        "VFclar",
        "VFclar_CA",
        "LuomingUS",
        "LuomingCA",
        "LuomingMX",
        "XiamoUK",
        "XiamoDE",
        "XiamoES",
        "XiamoFR",
        "XiamoIT",
        "JinFengUS",
        "JinFengCA",
        "YoungHorse_CA",
        "ZiningCA",
        "ZiningDE",
        "ZiningFR",
        "ZiningES",
        "ZiningIT",
        "ZheJiang_CA",
        "xiamoCA",
        "LiverpoolDE",
        "LiverpoolFR",
        "LiverpoolIT",
        "LiverpoolES"
    ]
    print model.CSaveData.DoSave()
    if not model.CSaveData.ReadSaveData():
        publog.error("需要初始化数据,请配置文件",define.CONFIG_FILE)

        return


if __name__ == "__main__":
    main()